[package]
name = "heightmap-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcg-mwc = "0.2.1"
ndarray = "0.15.6"
image = "0.24.8"
rand = "0.8.5"